export const southeastCities = [
  { slug: 'atlanta-ga', city: 'Atlanta', state: 'Georgia', stateAbbr: 'GA', region: 'Metro Atlanta' },
  { slug: 'savannah-ga', city: 'Savannah', state: 'Georgia', stateAbbr: 'GA', region: 'Coastal Georgia' },
  { slug: 'augusta-ga', city: 'Augusta', state: 'Georgia', stateAbbr: 'GA', region: 'Central Savannah River Area' },
  { slug: 'charlotte-nc', city: 'Charlotte', state: 'North Carolina', stateAbbr: 'NC', region: 'Charlotte metro' },
  { slug: 'raleigh-nc', city: 'Raleigh', state: 'North Carolina', stateAbbr: 'NC', region: 'Research Triangle' },
  { slug: 'durham-nc', city: 'Durham', state: 'North Carolina', stateAbbr: 'NC', region: 'Research Triangle' },
  { slug: 'greensboro-nc', city: 'Greensboro', state: 'North Carolina', stateAbbr: 'NC', region: 'Piedmont Triad' },
  { slug: 'wilmington-nc', city: 'Wilmington', state: 'North Carolina', stateAbbr: 'NC', region: 'Coastal North Carolina' },
  { slug: 'charleston-sc', city: 'Charleston', state: 'South Carolina', stateAbbr: 'SC', region: 'Lowcountry' },
  { slug: 'columbia-sc', city: 'Columbia', state: 'South Carolina', stateAbbr: 'SC', region: 'Midlands' },
  { slug: 'greenville-sc', city: 'Greenville', state: 'South Carolina', stateAbbr: 'SC', region: 'Upstate South Carolina' },
  { slug: 'myrtle-beach-sc', city: 'Myrtle Beach', state: 'South Carolina', stateAbbr: 'SC', region: 'Grand Strand' },
  { slug: 'nashville-tn', city: 'Nashville', state: 'Tennessee', stateAbbr: 'TN', region: 'Middle Tennessee' },
  { slug: 'knoxville-tn', city: 'Knoxville', state: 'Tennessee', stateAbbr: 'TN', region: 'East Tennessee' },
  { slug: 'chattanooga-tn', city: 'Chattanooga', state: 'Tennessee', stateAbbr: 'TN', region: 'Southeast Tennessee' },
  { slug: 'memphis-tn', city: 'Memphis', state: 'Tennessee', stateAbbr: 'TN', region: 'West Tennessee' },
  { slug: 'birmingham-al', city: 'Birmingham', state: 'Alabama', stateAbbr: 'AL', region: 'Central Alabama' },
  { slug: 'huntsville-al', city: 'Huntsville', state: 'Alabama', stateAbbr: 'AL', region: 'North Alabama' },
  { slug: 'mobile-al', city: 'Mobile', state: 'Alabama', stateAbbr: 'AL', region: 'Gulf Coast Alabama' },
  { slug: 'montgomery-al', city: 'Montgomery', state: 'Alabama', stateAbbr: 'AL', region: 'River Region' },
  { slug: 'jacksonville-fl', city: 'Jacksonville', state: 'Florida', stateAbbr: 'FL', region: 'Northeast Florida' },
  { slug: 'orlando-fl', city: 'Orlando', state: 'Florida', stateAbbr: 'FL', region: 'Central Florida' },
  { slug: 'tampa-fl', city: 'Tampa', state: 'Florida', stateAbbr: 'FL', region: 'Tampa Bay' },
  { slug: 'st-petersburg-fl', city: 'St. Petersburg', state: 'Florida', stateAbbr: 'FL', region: 'Tampa Bay' },
  { slug: 'miami-fl', city: 'Miami', state: 'Florida', stateAbbr: 'FL', region: 'South Florida' },
  { slug: 'fort-lauderdale-fl', city: 'Fort Lauderdale', state: 'Florida', stateAbbr: 'FL', region: 'South Florida' },
  { slug: 'west-palm-beach-fl', city: 'West Palm Beach', state: 'Florida', stateAbbr: 'FL', region: 'Palm Beaches' },
  { slug: 'tallahassee-fl', city: 'Tallahassee', state: 'Florida', stateAbbr: 'FL', region: 'Florida Panhandle' },
  { slug: 'pensacola-fl', city: 'Pensacola', state: 'Florida', stateAbbr: 'FL', region: 'Western Panhandle' },
  { slug: 'new-orleans-la', city: 'New Orleans', state: 'Louisiana', stateAbbr: 'LA', region: 'Southeast Louisiana' },
  { slug: 'baton-rouge-la', city: 'Baton Rouge', state: 'Louisiana', stateAbbr: 'LA', region: 'Capital Region' },
  { slug: 'jackson-ms', city: 'Jackson', state: 'Mississippi', stateAbbr: 'MS', region: 'Central Mississippi' },
];

export const findCityBySlug = slug => southeastCities.find(city => city.slug === slug);
